version: "3.7"
services:
  theserver:
    container_name: theserver
    build: ./apps/theserver
    command: npm run start:dev
    volumes:
      # this is for live reload if you're running locally
      # - ./apps/theserver:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - 7000
    ports:
      - 7000:7000
